theme: jekyll-theme-architect
title: Empowering communities in Eastern Uganda
description: Building cross-cultural friendships and lending a helping hand to people across Eastern Uganda 
logo: clothes.jpg
