theme: jekyll-theme-architect
title: A house for Arthur before the rains come
description: A website to raise money for (and publicize progress with) the "House for Arthur" building project
logo: clothes.jpg
