theme: jekyll-theme-architect
title: Helping those living in extreme poverty in Peta
description: A project to provide for the basic needs of a few individuals living in extreme poverty in the village of Peta, Uganda
logo: clothes.jpg
